name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  platform: ^3.1.0
  cupertino_icons: ^1.0.8
  http:
  shared_preferences: ^2.2.3
  fluttertoast: 8.2.6
  file_picker: 8.0.3
  flutter_launcher_icons:
  share:
  #flappy_search_bar:
  #flutter_read_more_text:
  dio:
  #webview_flutter: 0.3.21
  carousel_slider: ^4.2.1
  #flutter_multi_carousel:
  sliding_up_panel:
  #flutter_local_notifications: 3.0.1
  path_provider:
  flutter_plugin_android_lifecycle: ^2.0.20
  #firebase_messaging: ^7.0.3
  #firebase_core: ^3.0.0
  #firebase_analytics: ^8.0.0
  #flutter_inappwebview: ^4.0.0+4
  #flutter_switch: 0.1.1
  #forceupdate: ^0.0.6 commented
  #open_appstore: ^1.0.2 commented


  firebase_core: any
  forceupdate: any
  firebase_messaging: any
  path: any
  flutter_inappwebview: any
  webview_flutter: any
  flappy_search_bar: any
  flutter_local_notifications: any
  flutter_switch: any
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/ca/
    - assets/logo/cowdiar_logo.png
    - assets/1.jpg
    - assets/2.jpg
    - assets/7.jpg
    - assets/4.jpg
    - assets/icon1.png
    - assets/icon2.png
    - assets/icon3.png
    - assets/cover/cover1.jpg
    - assets/cover/cover2.jpg
    - assets/cover/cover3.jpg
    - assets/cover/cover4.jpg
    - assets/profile/profile1.jpg
    - assets/profile/profile2.jpg
    - assets/profile/profile3.jpg
    - assets/profile/profile4.jpg
    - assets/icons/home.png
    - assets/icons/homeact.png
    - assets/icons/inbox.png
    - assets/icons/inboxact.png
    - assets/icons/note.png
    - assets/icons/noteact.png
    - assets/icons/profile.png
    - assets/icons/profileact.png
    - assets/icons/search.png
    - assets/icons/searchact.png
    - assets/icons/cat.png
    - assets/data.json
  fonts:
    - family: SophiaNubian
      fonts:
        - asset: assets/font/SophiaNubian.ttf
    - family: ChunkFive
      fonts:
        - asset: assets/font/chunkfiveregular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
